# Generated by Django 4.2.3 on 2023-09-28 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_motorcycle_partsname_motorcycleparts_partname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motorcycleparts',
            old_name='description1',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='motorcycleparts',
            old_name='image1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='motorcycleparts',
            old_name='price1',
            new_name='price',
        ),
    ]
